### ISSUE TITLE
有个小错误

### ISSUE THREAD

**Issue by uuhhuu** [xiaolin199912/Resnet50-cats_vs_dogs#2]
这两个名字不一样
![屏幕截图 2024-06-24 225917](https://github.com/Zeyi-Lin/Resnet50-cats_vs_dogs/assets/164200143/b6019703-2c4c-42cd-9ad5-342083c47f15)

![屏幕截图 2024-06-24 225905](https://github.com/Zeyi-Lin/Resnet50-cats_vs_dogs/assets/164200143/2e404d17-5c91-40f6-9e38-3e60e92d4c60)

对了哥，那个标记按钮是什么作用呀，放进图片提交然后点了一下也没啥反应

**Comment by Zeyi-Lin** [comment]
> 这两个名字不一样 ![屏幕截图 2024-06-24 225917](https://private-user-images.githubusercontent.com/164200143/342390715-b6019703-2c4c-42cd-9ad5-342083c47f15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTUwMTQsIm5iZiI6MTcxOTQ5NDcxNCwicGF0aCI6Ii8xNjQyMDAxNDMvMzQyMzkwNzE1LWI2MDE5NzAzLTJjNGMtNDJjZC05YWQ1LTM0MjA4M2M0N2YxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMzI1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTQ0NzQ2YzQ1ZGRkMmY1YmQxY2U3MWJlMjg5MmI4NzIwMjI0MzcwYjRkMjM4NzYyYjQ3NTFiMjA0ODJkZjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hl4swbRhKUAtgpigd_V63W5hmZqCwjt5G3mIDM5xvp0)
> 
> ![屏幕截图 2024-06-24 225905](https://private-user-images.githubusercontent.com/164200143/342390701-2e404d17-5c91-40f6-9e38-3e60e92d4c60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTUwMTQsIm5iZiI6MTcxOTQ5NDcxNCwicGF0aCI6Ii8xNjQyMDAxNDMvMzQyMzkwNzAxLTJlNDA0ZDE3LTVjOTEtNDBmNi05ZTM4LTNlNjBlOTJkNGM2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMzI1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2Q3ZjZkYWEwZjA5NjFkNmE5ZjBjNjNhNGMwMDJlNzZiYzJhYWQ0NjY1OGIxNTg5MjRkYjEwZWFmYTI5ODY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yqum1IGRyteGJUpN4v39mEkVE1MZaX4WDVhAiRKahAQ)
> 
> 对了哥，那个标记按钮是什么作用呀，放进图片提交然后点了一下也没啥反应

1. 确实是，我改一下！
2. Gradio的标记按钮会把你当前的图片什么的记录到本地一个文件夹里

**Comment by uuhhuu** [comment]
明白了，谢谢哥

**Comment by Zeyi-Lin** [comment]
> 明白了，谢谢哥

不客气，感谢反馈
